# Generated by Django 2.1.5 on 2019-02-11 00:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('angel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginitem',
            name='id',
        ),
        migrations.AddField(
            model_name='loginitem',
            name='expired_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='angel',
            name='central_key',
            field=models.CharField(editable=False, max_length=64),
        ),
        migrations.AlterField(
            model_name='loginitem',
            name='angel',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='angel.Angel'),
        ),
        migrations.AlterField(
            model_name='loginitem',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
