# Generated by Django 2.1.5 on 2019-02-12 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angel', '0002_auto_20190211_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angel',
            name='central_key',
            field=models.CharField(editable=False, max_length=64, unique=True),
        ),
    ]
