# Generated by Django 2.1.5 on 2019-02-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angel', '0003_auto_20190212_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginitem',
            name='expired_time',
            field=models.DateTimeField(editable=False),
        ),
    ]
