# Generated by Django 2.1.7 on 2019-04-04 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('angel', '0005_angel_im_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('author', models.CharField(max_length=64)),
                ('updateAt', models.DateTimeField(blank=True, editable=False, null=True)),
                ('content', models.CharField(max_length=128)),
                ('angels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='angel.Angel')),
            ],
        ),
    ]
