# Generated by Django 2.1.7 on 2019-04-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='author',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='content',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
