# Generated by Django 2.1.7 on 2019-04-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('angel', '0005_angel_im_token'),
        ('info', '0003_auto_20190407_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('author', models.CharField(blank=True, max_length=64, null=True)),
                ('updateAt', models.DateTimeField(blank=True, editable=False, null=True)),
                ('content', models.CharField(blank=True, max_length=128, null=True)),
                ('angel', models.ManyToManyField(blank=True, to='angel.Angel')),
            ],
        ),
        migrations.RemoveField(
            model_name='info',
            name='angel',
        ),
        migrations.DeleteModel(
            name='Info',
        ),
    ]
