# Generated by Django 2.1.7 on 2019-04-08 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('angel', '0005_angel_im_token'),
        ('info', '0005_auto_20190407_0400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True)),
                ('angel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='angel.Angel')),
            ],
        ),
        migrations.RemoveField(
            model_name='board',
            name='angel',
        ),
        migrations.AddField(
            model_name='score',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Board'),
        ),
    ]
