# Generated by Django 2.1.7 on 2019-04-09 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_auto_20190408_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='score',
            new_name='scores',
        ),
    ]
