# Generated by Django 2.1.7 on 2019-04-15 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('angel', '0005_angel_im_token'),
        ('info', '0007_auto_20190409_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('value', models.CharField(max_length=32)),
                ('angel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='angel.Angel')),
            ],
        ),
        migrations.CreateModel(
            name='UpdateRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='score',
            name='angel',
        ),
        migrations.RemoveField(
            model_name='score',
            name='board',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='updatedAt',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='board',
            name='updatedAt',
        ),
        migrations.AddField(
            model_name='board',
            name='name',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.DeleteModel(
            name='Score',
        ),
        migrations.AddField(
            model_name='boarditem',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.Board'),
        ),
        migrations.AddField(
            model_name='boarditem',
            name='update',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='info.UpdateRecord'),
        ),
        migrations.AddField(
            model_name='board',
            name='update',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='info.UpdateRecord'),
        ),
    ]
