# Generated by Django 2.1.7 on 2019-04-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128)),
                ('dstLongitude', models.FloatField(editable=False)),
                ('dstLatitude', models.FloatField(editable=False)),
                ('srcLongitude', models.FloatField(editable=False)),
                ('srcLatitude', models.FloatField(editable=False)),
                ('cost', models.FloatField()),
                ('distrbution', models.FloatField()),
                ('status', models.IntegerField(choices=[(0, 'unpick'), (1, 'unfinish'), (2, 'unconfirm'), (3, 'confirm'), (-1, 'unpick-cancel'), (-2, 'pick-cancel'), (-3, 'finish-cancel')], default=-4)),
                ('owner', models.CharField(editable=False, max_length=16)),
                ('helper', models.CharField(editable=False, max_length=16)),
                ('createdAt', models.DateTimeField(editable=False)),
                ('finishedAt', models.DateTimeField(editable=False)),
                ('canceledAt', models.DateTimeField(editable=False)),
            ],
        ),
    ]
