# Generated by Django 2.1.7 on 2019-04-01 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='distrbution',
            new_name='distribution',
        ),
    ]
