# Generated by Django 2.1.7 on 2019-04-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20190401_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='canceledAt',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='dstLatitude',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='dstLongitude',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='finishedAt',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='helper',
            field=models.CharField(blank=True, editable=False, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='srcLatitude',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='srcLongitude',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
