# Generated by Django 2.1.7 on 2019-04-01 14:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20190401_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginItem',
            fields=[
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='task.Task')),
            ],
        ),
    ]
