# Generated by Django 2.1.7 on 2019-04-01 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_loginitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginitem',
            name='task',
        ),
        migrations.DeleteModel(
            name='LoginItem',
        ),
    ]
