# Generated by Django 2.1.7 on 2019-04-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_remove_task_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='owner',
            field=models.CharField(default=1, editable=False, max_length=16),
            preserve_default=False,
        ),
    ]
