# Generated by Django 2.1.7 on 2019-04-03 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_task_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='distribution',
            field=models.FloatField(default=0),
        ),
    ]
