# Generated by Django 2.1.7 on 2019-04-03 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_auto_20190403_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='distribution',
        ),
    ]
