# Generated by Django 2.1.7 on 2019-04-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_remove_task_distribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='distribution',
            field=models.FloatField(default=0),
        ),
    ]
