# Generated by Django 2.1.7 on 2019-04-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_task_distribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='helper',
            field=models.CharField(blank=True, default='', editable=False, max_length=16),
        ),
    ]
